### ISSUE TITLE
Identity Inserts

### ISSUE THREAD

**Issue by mikecasas** [alecgn/mssql-helpers#2]
Thanks for the great tool!

Is there a way to set the identity insert to on and then off after the query is run?

**Comment by alecgn** [comment]
Hey @mikecasas, thank you!

Surelly, I'm gonna add this feature and publish a new release asap.
Thank you for your feedback bro.

**Comment by alecgn** [comment]
@mikecasas done bro!
NuGet package: https://www.nuget.org/packages/MsSqlHelpers/1.3.1
Closing this.

**Comment by mikecasas** [comment]
Phenomenal! Thanks!
